### ISSUE TITLE
Roadmap - 2023.10

### ISSUE THREAD

**Issue by frezes** [WizTelemetry/whizard#382]
### 产品驱动的Feature
* [ ] **可观测中心后端基于 License 对监控规模限制**
      需求描述及Proposal: https://wiki.yunify.com/pages/viewpage.action?pageId=168122014

* [ ]  **支持非 KubeSphere Cluster 数据的接入, 细化对外部租户监控告警展示及权限控制**
  关联Issues:
  * [【可观测中心】细化对外部租户(非 KubeSphere Cluster)监控告警的权限与展示](https://github.com/kubesphere/project/issues/3990)
  * [【可观测中心】外部非 KSE 的监控数据的告警](https://github.com/kubesphere/issues/issues/1667)
  * [[多集群监控告警] 支持非 KubeSphere or KSE 集群](https://github.com/kubesphere/issues/issues/604)
* [ ] ~~Ruler 部署模式更灵活，支持对接入 VM 监控数据进行告警(包含在上述需求内)~~

### 迭代增强
* [x] WhizardTelemetry/whizard#424
         需求描述：当前 Whizard 使用 whizard-config 作为全局配置文件，但如果启用多个Service，各自Service 的独立配置无法定义，且无法处理ruler 与rule 的关联关系；因此需要简化全局配置，丰富Service 层级配置；
         Proposal:  暂缺
* [ ] [[Compactor] Support vertical compactions](https://github.com/WhizardTelemetry/whizard/issues/142)
* [ ] https://github.com/WhizardTelemetry/whizard/issues/387
* [ ] [提供 Remote Read 接口支持](https://github.com/WhizardTelemetry/project/issues/1) 
* [ ] 重构BaseReconciler， 支持container override，支持指定挂载configmap/secret，以达到新功能使用 override 方式能workaround(priority:medium)
* [ ] 社区跟进
